### ISSUE TITLE
just some suggestions for debug

### ISSUE THREAD

**Issue by hydra3333** [DeadSix27/python_cross_compile_script#102]
Hello. 
Just a patch with few suggestions which I am sure you're going to hate, however mention them in case there's something of use in there somewhere.

Changes:

lots of extra debugging statements, sometimes handy if manually replicating some part of a process
constrain mingw build to a known working commit, 'tags/v7.0.0'
provide for adding flags everywhere if worried about sources (yes, some performance hit):
```
	'original_cflags': '-O3',
	'original_stack_protector' : '-fstack-protector-all',
	'original_fortify_source'  : '-D_FORTIFY_SOURCE=2',  
```
add a 'custom_ldflag' allowing backout a specific dependency or two from the extra flags
add some potentially handy replacevars bits
in customFolder, where a folder exists the script crashes so just remove the folder

[just_suggestions.patch.txt](https://github.com/DeadSix27/python_cross_compile_script/files/3992011/just_suggestions.patch.txt)

**Comment by DeadSix27** [comment]
> constrain mingw build to a known working commit

I added a config file, which never gets overwritten and which I try to keep compatible for the foreseeable future, if you want to stay on a stable commit, just change the option:
```yaml
mingw_commit: null
```
to `tags/4.0.0` or so it will stay like that forever until you delete/change the config.
But i do not want to set a specific one in the repo, so i dont have to keep updating it to the latest stable version, whoever runs this script himself can do that then.

Currently I do not have a way to manage ldflags other than via `env..whatever`
But i did add
```py
'strip_cflags': ['-O3', ],
```
(EDIT: which apparently you extended in the patch, and actually saw as well, so nvm)

~~Which allows you to strip specific options from specific packages, e.g say you set this in .yaml:~~

```yaml
  original_cflags: -Ofast -march=skylake
```
~~You can then set:~~
~~`'strip_cflags': ['-march=skylake', ],` in goofyPackage.py and said package will only be build with -Ofast.~~

~~Does not work for LDFLAGS yet though, ill look into that, since some ENV vars like LDFLAGS are actually used in quite a few packages.. so they're worth having a specific option for.~~

the patch looks fine though, can you split it into 2? Remove the LDFLAGS stuff and first make a PR for the extra debug stuff, then after that one for the ldflags stuff, but put it in a PR so i can push to it as  well without much effort in case theres something to reformat/change.

**Comment by hydra3333** [comment]
ok. may take a bit given the date :)

Wishing you a Happy Christmas !!

**Comment by hydra3333** [comment]
hopefully that worked, a pull with 2 commits.
https://github.com/DeadSix27/python_cross_compile_script/pull/103
