### ISSUE TITLE
interesting comment about tesseract and cmake

### ISSUE THREAD

**Issue by hydra3333** [DeadSix27/python_cross_compile_script#105]
hello, just an fyi

https://github.com/m-ab-s/media-autobuild_suite/issues/1509#issuecomment-570240320

**Comment by DeadSix27** [comment]
How is it relevant to me? It seems like it fails on their end not mine?
Works fine in my script anyway and yes I use cmake over autotools as that also works fine for my usage case.

I do not have 32bit support and do not use shared curl (and don't intend to, not worth encouraging use of 32bit these days...) and shared nghttp2 would require having the said lib around, which is a bit annoying since it's not standard on windows.

`ffprobe -f lavfi -i movie=testimg.png,ocr -show_entries frame=pkt_dts_time:frame_tags=lavfi.ocr.text -of json`

=
```
Input #0, lavfi, from 'movie=testimg.png,ocr':
  Duration: N/A, start: 0.000000, bitrate: N/A
    Stream #0:0: Video: rawvideo (444P / 0x50343434), yuv444p, 557x155 [SAR 1:1 DAR 557:155], 25 tbr, 25 tbn, 25 tbc
    "frames": [
        {
            "pkt_dts_time": "0.000000",
            "tags": {
                "lavfi.ocr.text": "Testmessage\n"
            }
        }[Parsed_movie_0 @ 000001d1be35b780] EOF timestamp not reliable

    ]
}
```

testimg.png:
![testimg](https://user-images.githubusercontent.com/1492505/72141010-455a2980-3392-11ea-9fab-0bcfedd1b124.png)
