### ISSUE TITLE
default package version of cmake is too low to build libflac under Ubuntu 18.04.3

### ISSUE THREAD

**Issue by hydra3333** [DeadSix27/python_cross_compile_script#107]
Hello.  
Under Ubuntu 18.04.3, the default package version of cmake is too low to build libflac and it aborts.
For other people who may need to build cmake themselves, I had to build the latest supported version of cmake thus:

```
# Build and install the latest supported cmake
rm -vfR cmake-3.16.5
mkdir cmake-3.16.5
cd cmake-3.16.5
echo "Downloading cmake-3.16.5"
sudo apt install -y libssl-dev 
sudo apt remove -y cmake
curl -4 -H 'Pragma: no-cache' -H 'Cache-Control: no-cache' -H 'Cache-Control: max-age=0' "https://github.com/Kitware/CMake/releases/download/v3.16.5/cmake-3.16.5.tar.gz" -L -O
tar -xf cmake-3.16.5.tar.gz
sudo chmod +777 -R *
cd cmake-3.16.5 # unzipped subfolder
   #./bootstrap --help
   ./bootstrap --prefix=/usr && make && sudo make install
cd ..
echo "Done Installing cmake-3.16.5"
cd ..
```

**Comment by hydra3333** [comment]
perhaps a warning or something ?

**Comment by DeadSix27** [comment]
While useful, it would be  a lot of work, because If I warned of specific versions of one programs.. I would want to warn of required programs and their versions for every package... and that also would require new code (apart from the massive task that is finding out what requires what)

And lately I am too lazy to add new stuff to the code itself.. I'd rather rewrite the whole thing (which is why i haven't touched your PR)

**Comment by hydra3333** [comment]
cool
