### ISSUE TITLE
This project vs Meson

### ISSUE THREAD

**Issue by Eloston** [DeadSix27/python_cross_compile_script#2]
What is the benefit of this system as opposed to something like [Meson](http://mesonbuild.com/)?

I don't want to shoot down your project. Just curious about your vision for this.

**Comment by DeadSix27** [comment]
@Eloston Meson isn't made by myself. I never heard of it, nor used it. 

Mine would be best compared to "MXE" which is another influencer of this, however MXE as well as this, depends on a pre-made list of packages it "can xcompile" and the issue being, a lot of them are outdated in MXE. Which is why, instead of helping the imo horrible MXE, I just made my own with newer dependencies. 

EDIT: By looking 10seconds in to Meson I am also unsure whether it has support to work-around compile quirks, e.g the need to make your own PKG-conf file or sed some things.

EDIT2: As to the reason why I even uploaded this on github? Mainly because I felt like it.
Usually I write many projects like this in private and never ever release them, but I figured, might as well use github as a backup and as bonus share it with people.
(Which is why I also used such a restrictive License)

**Comment by Eloston** [comment]
I don't know much about the packaging capabilities, but you can invoke any commands you want from Meson.

I haven't personally used Meson, but it's quite similar to GN or GYP from Google. I also think the syntax with GN and Meson is easier to use than JSON and GYP. Because of the robustness of GN, I think Meson might be a worthy investment. Also, it saves you the work of re-inventing the wheel again.

**Comment by DeadSix27** [comment]
@Eloston I do not like GN or GYP from google from what I experienced with ungoogled. 
And I love json as well as python for its simplicity. 
Quite sure GN needs way more work in the future to stay working.
While the only thing that really prevents my script from working, is the mingw build script (which I could port as well If I could bother) or python changing dramatically.

Also, read EDIT1-2 of my previous post.

**Comment by Eloston** [comment]
> I do not like GN or GYP from google from what I experienced with ungoogled.

What don't you like about them?

> Quite sure GN needs way more work in the future to stay working.

What do you mean by this?

> Also, read EDIT1-2 of my previous post.

I have addressed that in the first line of my post

**Comment by DeadSix27** [comment]
> What don't you like about them?

I do not know how to use it without reading a documentation or readme.
This program is going to be something users can just.. start.
Quite sure you can't just start GYP/GN and tell it to make ffmpeg or mpv or curl, can you?

> I have addressed that in the first line of my post

Have you? EDIT2, clearly answers any question you have and will have, doesn't it?

**Comment by Eloston** [comment]
> Quite sure you can't just start GYP/GN and tell it to make ffmpeg or mpv or curl, can you?

Meson, GN, and GYP are not build commands. They are meta-build generators; they generate ninja files. Ninja does the actual building

Also, [using Meson doesn't have to be that complicated](https://github.com/mesonbuild/meson/wiki/Quick%20guide)

> Have you? EDIT2, clearly answers any question you have and will have, doesn't it?

Oh I forgot to reload the page.

**Comment by DeadSix27** [comment]
@Eloston 

Isn't GYP/GN a compiler helper (is that a meta-build generator?) 
E.g cmake/make and configure as well as waf? Doesn't GN/GYP belong in there?

As you mentioned "ninja files" are they comparable to Makefiles which are generated from Makefile.in files?

If so:
My script as well as MXE and build-helper (linked in README) are all wrappers for c/make/etc ? E.g they use the clunky lib by lib, project by project steps and make it all one command to build it all.

EDIT: To make where I'm going with this clearer.
My script builds things using GN/GYP, e.g its 1 layer above it. It can build many GN projects and make it a 1 command and go thing.
And not only GN also cmake and make and waf, thats the idea.

**Comment by Eloston** [comment]
Oh I see. So this project is pretty similar to what ungoogled-chromium has for building. Nevermind then, I misunderstood the intent of the project.

**Comment by DeadSix27** [comment]
@Eloston Exactly! its like your python script that builds ungoogled.

**Comment by DeadSix27** [comment]
@Eloston Also to clarify something else: `Why not MXE or ffmpeg-helper why your own thing?`
Because MXE is outdated and ffmpeg-helper has limitations of bash.
And I try to make it more reliable so that I can run this all in my jenkins server and don't have to worry about it anymore and if a Library needs an update? Well I just have to update the JSON and not the entire build script as in ffmpeg-helpers case, or have to worry about the messy system that is MXE (where you can not even add a project without adding it to a weird as hell HTML list..)

**Comment by Eloston** [comment]
Hm, sounds like ungoogled-chromium's build system in its purpose but with the feature like Meson to have components separated from one another. Interesting.
