### ISSUE TITLE
some testing on ubu 16.10

### ISSUE THREAD

**Issue by thaodean** [DeadSix27/python_cross_compile_script#5]
Hi DeadSix27,

I like your approach.

A few comments:
It really needs prereq check.
It would be also really nice to make it somehow easier to add/remove libs.
FFmpeg also gets consistently around 5% faster encoding speed with x264 video only than my previous build, no idea why, posix?

thanks

On Ubu 16.10:

1. vamp and rubberband failing with :
    cflag_string              = self.generateCflagString('--extra-cflags=')
KeyError: 'compile_prefix_sed_escaped'

2. flac missed libtools  Missing program 'libtool'

apt install libtool
Reading package lists... Done
Building dependency tree
Reading state information... Done
libtool is already the newest version (2.4.6-1)

3.some packages missed 'gyp' and 'gperf'

4. vorbistools fails

5. libflac fails

6. libfdk_aac is build but not enabled by default?

7 mkvtoolnix also needs docbook-xsl apart from docbook-utils

8 mkvtoolnix link fails with
        LINK src/mkvtoolnix-gui/mkvtoolnix-gui.exe
[2017-04-10 03:08:00,302][ERROR] Error [127] running process: 'rake  -j 8'

**Comment by thaodean** [comment]
Oh and what are all those patches in a nutshell?
thx

**Comment by thaodean** [comment]
**[2017-04-10 03:31:14,954][ERROR] Error [1] running process: 'patch -p1 < "openal-soft-privlibs.patch"'**
NoneType: None
Traceback (most recent call last):
  File "./m2.py", line 2729, in <module>
    main.commandLineEntrace()
  File "./m2.py", line 142, in commandLineEntrace
    self.defaultEntrace()
  File "./m2.py", line 158, in defaultEntrace
    main.produceProduct(p)
  File "./m2.py", line 167, in produceProduct
    self.build_product(p,self.PRODUCTS[p])
  File "./m2.py", line 886, in build_product
    self.build_depend(libraryName,self.DEPENDS[libraryName])
  File "./m2.py", line 781, in build_depend
    self.apply_patch(p[0],p[1],False,self.getValueByIntOrNone(p,2))
  File "./m2.py", line 1147, in apply_patch
    self.run_process('patch {2}-{0} < "{1}"'.format(type, fileName, ignore ),ignoreErr,exitOn)
  File "./m2.py", line 436, in run_process
    raise
RuntimeError: No active exception to reraise

**Comment by DeadSix27** [comment]
@mikemyers9 I only tested on 16.10 ubuntu yet and there is no package checking as of now, (I still have to implement that, check the comments at the very top, there should be a rough list of packages you need) or check the script of RDP for packages.. should be fine.
And yes, openal is not working atm, unfortunately, noticed that today too.. I will fix the patch tomorrow.

**Comment by DeadSix27** [comment]
@mikemyers9 I updated the patch for openal: 

Delete the openal_soft git folder and re-run the script.

EDIT: libfdk_aac is not included, its not allowed in a GPL licensed build. So I just didn't include it at all., its very easy to add yourself tho, you can do a pull request if you implemented it if you want. (so at least the code is there and people only have to add that to the dependency)

EDIT2: Check newest commits.
https://github.com/DeadSix27/modular_cross_compile_script/commit/fb3d1911a78d64a46cea1ca5325bba4f94912c1e
and
https://github.com/DeadSix27/modular_cross_compile_script/commit/a84e69b1f8c5ffcc2a5dc8ba0384545ca61a5b81
and 
https://github.com/DeadSix27/modular_cross_compile_script/commit/c94784d5a10725157d969b03a2479e80b4998d7b
and
https://github.com/DeadSix27/modular_cross_compile_script/commit/8160b343839fcb743f4846dceda3ab2f1ef65b93

EDIT3: tl;dr:
 - I do not use FDK-AAC (nonGPL)
 - Update to newest commit of my script
 - OpenAL is fixed
 - Package detection isn't a thing yet (Use rdp's script for a list of packages you need (and gyp/+ the ones in my script as comment at top)
 - About the faster ffmpeg, its because of cflags probably? -O3 and -march skylake.. it uses better instruction sets? idk, I'm not a ffmpeg/x264 dev.

Also if you do not need one of those programs, just remove them of product_order.. e.g only leave ffmpeg_static or w/e

**Comment by thaodean** [comment]
I used -march skylake +-O3 before just as well.
It must be something with x264.
I was using the product order, first I thought it was for the order in which they would be built, which it is as well :)
I will test, thanks

**Comment by DeadSix27** [comment]
@mikemyers9 Ye, I don't know why, maybe the different threading support actually does make it slightly faster, in which way that's a good thing f or you I guess? I added it mainly because of vapoursynth, which in the end I do not build anyway.
Also, the product_order is the order they're build in and also WHETHER they're build :)
So you can just put ffmpeg_static in and it will only build ffmpeg and its deps.

About packages, I began work on finding out which OS needs which packages ( see bottom )

also, VLC and its dependencies are not working currently, so don't wonder if that fails. (its disabled in the newest commit)

```
global      - texinfo yasm git make automake gcc gcc-c++ pax cvs svn flex bison patch libtoolize nasm hg cmake gettext-autopoint
mkvtoolnix  - libxslt docbook-util rake docbook-style-xsl
gnutls      - gperf
angle       - gyp
vapoursynth - p7zip
```

**Comment by DeadSix27** [comment]
I assume this is resolved :)? If not just say so and I'll reopen it!
