### ISSUE TITLE
Make Mediainfo actually build a windows .dll

### ISSUE THREAD

**Issue by DeadSix27** [DeadSix27/python_cross_compile_script#55]
As described on mxe's tracker long ago: https://github.com/mxe/mxe/issues/1746

I only get mediainfo to build a mingw import library (or so) rather than the proper windows dll.

If you know how to get it working, I'd appreciate patches for it. (I'm unable to figure it out)

EDIT: Oh and also discussed here: https://github.com/MediaArea/MediaInfo/issues/148

**Comment by hydra3333** [comment]
Unrelated but possibly interesting anecdote ...
https://github.com/DeadSix27/python_cross_compile_script/issues/75#issuecomment-423179119

Went to build fftw3 DLLs using this script system and instead of the DLLs being circa 2Mb (as provided in their windows binaries download) they were many many times that size.  Unsure if that result is related to the build system or something else.  Be interesting to see if that result also applies to a build of the mediainfo DLL.

**Comment by hydra3333** [comment]
Ah, changed "-ggdb -O3" to "-O3" and the large files sizes went away.  

Can't recall if the mediainfo build in the latest pull request actually builds a .dll.  It may ?  Probably not.
