### ISSUE TITLE
libressl patch by shinchiro no longer exists

### ISSUE THREAD

**Issue by hydra3333** [DeadSix27/python_cross_compile_script#77]
This patch
https://raw.githubusercontent.com/shinchiro/mpv-winbuild-cmake/master/packages/libressl-0001-ignore-compiling-test-and-man-module.patch
no longer exists

I guess a sed, or copy the patch locally from the pre-delete commit (the patch still applies) ?

**Comment by DeadSix27** [comment]
@hydra3333 See: https://github.com/DeadSix27/python_cross_compile_script/commit/d1cf7935b1b4ef98d737a2dedd4671a7d08600c1

Also he probably removed the patch because its not needed anymore or he ditched libressl, check his repo, I followed his patches for mpv and libressl before but later just used my own for mpv stuff.

**Comment by hydra3333** [comment]
yes, looks like build systems changed.  
the patch still applies to ordinary configure and make but was simply removed.
IIRC libressl may be used indirectly in building mediainfo

**Comment by hydra3333** [comment]
> # NOTE: Development is currently on halt or very slow, as I have lost my main development system/server. I will return around February 2019 most likely.

Eek, good luck with that !
